### ISSUE TITLE
Round Payment Fees

### ISSUE THREAD

**Issue by michelhonold** [mcguffin/woocommerce-payforpayment#32]
Hi,

I think it would be a nice feature to be able to round payment fees up to have looking prices. Options could be to rund on 1/100 (= like it happens now), 1/10 (on the next 10 cents) or 1 (on the next 1 $) of the currency.

**Comment by mcguffin** [comment]
HI,
thanks for the suggestion. I don't think rounded would be a common use case, and so I don't really feel like complicating the user interface with even more options. In my opinion it would be pretty unfair to your customers, when let's say 4.01 $ is rounded up to 5 $ (almost 20% more!), and I would think twice before buying in such a shop. 

If you really desire round up payment fees, you can do so using the [woocommerce_pay4pay_{$current_gateway_id}_amount](https://github.com/mcguffin/woocommerce-payforpayment#filter-woocommerce_pay4pay_current_gateway_id_amount) filter.
