### ISSUE TITLE
Outdated plugin - helping hand

### ISSUE THREAD

**Issue by vyskoczilova** [mcguffin/woocommerce-payforpayment#44]
Hi, I have found your plugin and used it for my client. I had to fix few issues anyway so I would love to give you a helping hand. I hope that the thread is not dead. If you don't have time for it anymore, I can take over or be a co-author also at WordPress repo. It's a shame that you didn't accept the pull with the change for WC newer 2.6, it would be so great to implement it and update the repo again.
I pulled a Czech translation of plugin.

**Comment by diggy** [comment]
@mcguffin ping!

**Comment by vyskoczilova** [comment]
@mcguffin @diggy  No answer? It's really a pitty.

**Comment by diggy** [comment]
Guess it's forking time

**Comment by vyskoczilova** [comment]
@diggy I already forked, however, do you know if there is a legal way how to become co-author in non-updating WordPress plugin? He (@mcguffin) is active on Github, it's not that complicated to spend a word here.

**Comment by diggy** [comment]
@vyskoczilova that's the slow path, what about fork and rename?

**Comment by vyskoczilova** [comment]
@diggy my repo is completely updated and compatible with WC 3.0 (you can test if you have time) I will try to take over, maybe it will not take that long. It has around 7000 downloads it would be a shame.

**Comment by diggy** [comment]
Alright! I'm hoping for the best :)

NB: I noticed you incorporated some pulls from other people, not sure if you noticed [this comment](https://github.com/mcguffin/woocommerce-payforpayment/pull/42#issuecomment-289494194)?

**Comment by vyskoczilova** [comment]
@diggy Ah, haven't seen it. Would you mind trying to replace the part of the code with following (and testing on 2.6+? It should be around lines 207-215 in admin/class-pay4pay-admin.php

```
function update_payment_options() {
global $current_section;
		if ( version_compare( WC_VERSION, '2.6', '<' )) { 
			$class = new $current_section();
			$class_id = $class->id;
		} else {
			$class_id = $current_section;
		}		
		$prefix = 'woocommerce_'.$class_id;
```

**Comment by vyskoczilova** [comment]
@diggy It was quite quick, I've got the plugin already Friday, I'm going to update the readme and pull it into official repository if you find anything to fix, let me know. And thanks for your support.

**Comment by vyskoczilova** [comment]
Added to the newest version of plugin: https://github.com/vyskoczilova/woocommerce-payforpayment
